server {
    listen 8000 default_server;
    listen [::]:8000 default_server;
    server_name tinnguyen.exe.xyz;
    root /srv/tinnguyen/current;
    index index.html;
    charset utf-8;
    server_tokens off;
    autoindex off;
    client_max_body_size 1m;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options DENY always;
    add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'sha256-h3GYPBFE6Av6zUWOZYeC83lN95g5tnhsj1pyM3woz/c=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'; form-action 'none'" always;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location ~ /\. {
        deny all;
    }
}
